### ISSUE TITLE
SSL support on UA server is raising errors

### ISSUE THREAD

**Issue by shyba** [pixelated/pixelated-user-agent#383]
$ pixelated-user-agent --config=my.conf --host 0.0.0.0 --debug -sk server.key -sc server.crt
Outputs:
```
2015-04-23 13:56:02+0000 [-] Unhandled Error
        Traceback (most recent call last):
          File "/home/vagrant/user-agent-venv/local/lib/python2.7/site-packages/Twisted-13.2.0-py2.7-linux-x86_64.egg/twisted/internet/base.py", line 1201, in mainLoop
            self.runUntilCurrent()
          File "/home/vagrant/user-agent-venv/local/lib/python2.7/site-packages/Twisted-13.2.0-py2.7-linux-x86_64.egg/twisted/internet/base.py", line 824, in runUntilCurrent
            call.func(*call.args, **call.kw)
          File "/home/vagrant/user-agent-venv/local/lib/python2.7/site-packages/Twisted-13.2.0-py2.7-linux-x86_64.egg/twisted/internet/defer.py", line 382, in callback
            self._startRunCallbacks(result)
          File "/home/vagrant/user-agent-venv/local/lib/python2.7/site-packages/Twisted-13.2.0-py2.7-linux-x86_64.egg/twisted/internet/defer.py", line 490, in _startRunCallbacks
            self._runCallbacks()
        --- <exception caught here> ---
          File "/home/vagrant/user-agent-venv/local/lib/python2.7/site-packages/Twisted-13.2.0-py2.7-linux-x86_64.egg/twisted/internet/defer.py", line 577, in _runCallbacks
            current.result = callback(current.result, *args, **kw)
          File "/vagrant/service/pixelated/config/__init__.py", line 74, in start_user_agent_app
            app_factory.create_app(app, args, leap_session)
          File "/vagrant/service/pixelated/config/app_factory.py", line 134, in create_app
            listen_with_ssl(app, args)
          File "/vagrant/service/pixelated/config/app_factory.py", line 156, in listen_with_ssl
            reactor.listenSSL(args.port, Site(app.resource), _ssl_options(args), interface=args.host)
          File "/vagrant/service/pixelated/config/app_factory.py", line 148, in _ssl_options
            acceptable = ssl.AcceptableCiphers.fromOpenSSLCipherString(
        exceptions.AttributeError: 'module' object has no attribute 'AcceptableCiphers'
```
Probably a change in our dependencies broke code from #149 

Expected definition of done:
=========
No errors. SSL support enabled and following #149 requirements.

**Comment by re-nobre** [comment]
This is a good idea but it isn't our focus now. 
Our focus now is the migration of Bitmask libraries latest version to Pixelated code.

I'll close this issue for now, it might be reopened in the future if it makes sense.
